package personaAPP;


/**
* personaAPP/personaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 23 de abril de 2018 07:43:47 PM COT
*/

public interface personaOperations 
{
  boolean insertarpersona (int identificacion, String nombre, String apellido, String direccion);
  String consultarpesona (int identificacion);
  boolean eliminarpersona (int identificacion);
  boolean actualizarpersona (int identificacion);
  String listarpersonas ();
  void shutdown ();
} // interface personaOperations
