package personaAPP;

/**
* personaAPP/personaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 23 de abril de 2018 07:43:47 PM COT
*/

public final class personaHolder implements org.omg.CORBA.portable.Streamable
{
  public personaAPP.persona value = null;

  public personaHolder ()
  {
  }

  public personaHolder (personaAPP.persona initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = personaAPP.personaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    personaAPP.personaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return personaAPP.personaHelper.type ();
  }

}
